# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ar_condicionado.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61r_condicionado.proto\"\x1a\n\x07\x43omando\x12\x0f\n\x07\x63omando\x18\x01 \x01(\t2<\n\x15\x41rCondicionadoService\x12#\n\rEnviarComando\x12\x08.Comando\x1a\x08.Comandob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ar_condicionado_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMANDO']._serialized_start=25
  _globals['_COMANDO']._serialized_end=51
  _globals['_ARCONDICIONADOSERVICE']._serialized_start=53
  _globals['_ARCONDICIONADOSERVICE']._serialized_end=113
# @@protoc_insertion_point(module_scope)
