version: '3.7'

services:
  #rabbitmq:
  #  container_name: "docker_rabbitmq"
  #  image: rabbitmq:3-management-alpine
  #  restart: always
  #  ports:
  #    - '5673:5672'

  sensor_temperatura:
    container_name: "docker_sensor_temperatura"
    build:
      context: ../sensores/temperatura
      dockerfile: temperatura.dockerfile
    restart: always
    ports:
      - '3010:3010'

  ar_condicionado:
    container_name: "docker_ar_condicionado"
    build:
      context: ../atuadores/ar-condicionado
      dockerfile: ar.dockerfile
    restart: always
    ports:
      - '3011:3011'
    depends_on:
      - sensor_temperatura

  servidor_grpc_temperatura:
    container_name: "docker_servidor_grpc_temperatura"
    build:
      context: ../servidores-grpc/ar-condicionado
      dockerfile: ar.dockerfile
    restart: always
    ports:
      - '50051:50051'
    depends_on:
      - ar_condicionado

  servidor_http:
    container_name: "docker_http"
    build:
      context: ../servidor-http
      dockerfile: http.dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - servidor_grpc_temperatura
