# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mensagem_pb2 as mensagem__pb2


class LampadaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarComando = channel.unary_unary(
                '/LampadaService/EnviarComando',
                request_serializer=mensagem__pb2.Comando.SerializeToString,
                response_deserializer=mensagem__pb2.Comando.FromString,
                )


class LampadaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnviarComando(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LampadaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarComando': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarComando,
                    request_deserializer=mensagem__pb2.Comando.FromString,
                    response_serializer=mensagem__pb2.Comando.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LampadaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LampadaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnviarComando(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LampadaService/EnviarComando',
            mensagem__pb2.Comando.SerializeToString,
            mensagem__pb2.Comando.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
